# Permalinks
permalink:        /:title.html

# Setup
title:            Math, CS, Statsitics, and the occasional book review
tagline:          'The website of Joe Misiti'
description:      'Joe is a software engineer living in lower manhattan that specializes in machine learning, statistics, python, and computer vision.'
url:              http://josephmisiti.github.io

# Build settings
markdown: kramdown
permalink: /:title
